package com.defensemanagement.academic.student.entity;

public enum EMajor {
    LICENCE_BIG_DATA,
    LICENCE_MULTIMEDIA,
    MASTER_SOFTWARE_ENGINEERING,
    MASTER_ARTIFICIAL_INTELLIGENCE,
    ENGINEERING_COMPUTER_SCIENCE,
    DOCTORATE_COMPUTER_SCIENCE
}
