spring:
  application:
    name: auth-service

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:auth_db}
    username: ${DB_USER:auth_user}
    password: ${DB_PASS:auth_pass}

  jpa:
    hibernate:
      ddl-auto: create          # never use create/update in anything beyond first run
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null
  web:
    error:
      include-message: never        # never leak stack traces to clients
   
server:
  port: 8085
application:
  security:
    jwt:
      secret-key: dGhpc2lzYXZlcnlzZWN1cmVzZWNyZXRrZXlmb3JqV1RhY2Nlc3N0b2tlbmdlbmVyYXRpb25hbGdvcml0aG0=
      access-token-expiration: 900000
      refresh-token-expiration: 604800000

internal:
  secret: MY_SUPER_SECRET_123