export enum Role {
  ADMIN = 'ADMIN',
  PROFESSOR = 'PROFESSOR',
  STUDENT = 'STUDENT'
}

export enum Major {
  LICENCE_BIG_DATA = 'LICENCE_BIG_DATA',
  LICENCE_MULTIMEDIA = 'LICENCE_MULTIMEDIA',
  MASTER_SOFTWARE_ENGINEERING = 'MASTER_SOFTWARE_ENGINEERING',
  MASTER_ARTIFICIAL_INTELLIGENCE = 'MASTER_ARTIFICIAL_INTELLIGENCE',
  ENGINEERING_COMPUTER_SCIENCE = 'ENGINEERING_COMPUTER_SCIENCE',
  DOCTORATE_COMPUTER_SCIENCE = 'DOCTORATE_COMPUTER_SCIENCE'
}

export enum DefenseStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  PLANNED = 'PLANNED'
}

export enum Mention {
  TRES_HONORABLE = 'TRES_HONORABLE',
  HONORABLE = 'HONORABLE',
  PASSABLE = 'PASSABLE',
  AJOURNE = 'AJOURNE',
  FAIRLY_GOOD = 'FAIRLY_GOOD'
}

export enum JuryRole {
  PRESIDENT = 'PRESIDENT',
  RAPPORTEUR = 'RAPPORTEUR',
  EXAMINATEUR = 'EXAMINATEUR',
  ENCADRANT = 'ENCADRANT'
}
