export enum Role {
  ADMIN = 'ADMIN',
  PROFESSOR = 'PROFESSOR',
  STUDENT = 'STUDENT'
}

export enum Major {
  LICENCE_BIG_DATA = 'LICENCE_BIG_DATA',
  LICENCE_MULTIMEDIA = 'LICENCE_MULTIMEDIA',
  MASTER_SOFTWARE_ENGINEERING = 'MASTER_SOFTWARE_ENGINEERING',
  MASTER_ARTIFICIAL_INTELLIGENCE = 'MASTER_ARTIFICIAL_INTELLIGENCE',
  ENGINEERING_COMPUTER_SCIENCE = 'ENGINEERING_COMPUTER_SCIENCE',
  DOCTORATE_COMPUTER_SCIENCE = 'DOCTORATE_COMPUTER_SCIENCE'
}

export enum DefenseStatus {
  PLANNED = 'PLANNED',
  ONGOING = 'ONGOING',
  PUBLISHED = 'PUBLISHED'
}

export enum Mention {
  FAIL = 'FAIL',
  PASSABLE = 'PASSABLE',
  FAIRLY_GOOD = 'FAIRLY_GOOD',
  GOOD = 'GOOD',
  VERY_GOOD = 'VERY_GOOD',
  EXCELLENT = 'EXCELLENT'
}

export enum JuryRole {
  PRESIDENT = 'PRESIDENT',
  RAPPORTEUR = 'RAPPORTEUR',
  EXAMINATEUR = 'EXAMINATEUR',
  ENCADRANT = 'ENCADRANT'
}
