spring:
  application:
    name: defense-service

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:defense_db}
    username: ${DB_USER:defense_user}
    password: ${DB_PASS:defense_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null
  web:
    error:
      include-message: never

server:
  port: 8084

services:
  academic:
    base-url: ${ACADEMIC_SERVICE_URL:http://localhost:8082}
  room:
    base-url: ${ROOM_SERVICE_URL:http://localhost:8083}

application:
  security:
    jwt:
      secret-key: dGhpc2lzYXZlcnlzZWN1cmVzZWNyZXRrZXlmb3JqV1RhY2Nlc3N0b2tlbmdlbmVyYXRpb25hbGdvcml0aG0=
